#!/bin/bash
#
# Teardown: remove the gomang service and uninstall etcd.
#
# Steps:
#   1. Stop (and disable) the gomang service, then remove its unit file
#      (/etc/systemd/system/gomang.service, generated by `gomang install`)
#      and daemon-reload. The unit file is removed manually rather than via
#      `gomang uninstall` — more deterministic.
#   2. Stop etcd, then uninstall it via yum (also cleans /etc/etcd)
#
# Notes:
#   - /var/lib/etcd (etcd data) is REMOVED so no state carries over to the next
#     run (users, auth-enabled flag, stale keys).
#   - gomang is only stopped, not uninstalled; /etc/gomang is preserved.
#
# Must run as root.

set -euo pipefail

GOMANG_SERVICE="gomang"
ETCD_SERVICE="etcd"

# ---- Root check ----
if [[ $EUID -ne 0 ]]; then
    echo "Error: must run as root (use sudo)" >&2
    exit 1
fi

# ---- 1. Stop gomang and remove its unit file ----
echo "[1/2] Stopping and removing ${GOMANG_SERVICE}"
if systemctl cat "${GOMANG_SERVICE}.service" >/dev/null 2>&1; then
    systemctl stop "${GOMANG_SERVICE}" || true
    systemctl disable "${GOMANG_SERVICE}" 2>/dev/null || true
    echo "      stopped and disabled"
else
    echo "      service ${GOMANG_SERVICE} not found, skipping"
fi

# Remove the unit file generated by `gomang install` (kardianos/service) and
# refresh systemd so the removal takes effect. rm -f is a no-op if absent.
UNIT_FILE="/etc/systemd/system/gomang.service"
rm -f "${UNIT_FILE}"
systemctl daemon-reload
echo "      removed ${UNIT_FILE} and reloaded systemd"

# ---- 2. Uninstall etcd ----
echo "[2/2] Uninstalling etcd"

# Stop the service first if present
if systemctl cat "${ETCD_SERVICE}.service" >/dev/null 2>&1; then
    systemctl stop "${ETCD_SERVICE}" || true
    systemctl disable "${ETCD_SERVICE}" 2>/dev/null || true
    echo "      etcd service stopped and disabled"
fi

# Remove the package if installed
if rpm -q etcd >/dev/null 2>&1; then
    yum remove -y etcd
    echo "      package removed"
else
    echo "      etcd package not installed, skipping"
fi

# Clean leftover config dir (yum usually leaves /etc/etcd behind)
if [[ -d /etc/etcd ]]; then
    rm -rf /etc/etcd
    echo "      removed /etc/etcd"
fi

# Remove the data dir too, so no state (users, auth flag, stale keys) survives
# to the next run. setup also wipes it, but cleaning up here keeps teardown fully
# restoring the environment.
if [[ -d /var/lib/etcd ]]; then
    rm -rf /var/lib/etcd
    echo "      removed /var/lib/etcd"
fi

echo "----"
echo "Done."
